### ISSUE TITLE
Invalid custom elements possible with current implementaton

### ISSUE THREAD

**Issue by JakobVogelsang** [bashmish/carehtml#36]
The [syntax for custom elements](https://html.spec.whatwg.org/#valid-custom-element-name) must start with `[a-z]`. This is not always the case with carehtml at the moment. We have found an issue with the following example:

`_BayEditor` -> `_-bay-editor`

**Comment by bashmish** [comment]
@JakobVogelsang do I get correctly that you had a class with name `_BayEditor`? Like using `const _BayEditor = class { ... }`?

**Comment by bashmish** [comment]
Released in 0.1.5, hope it helps!
